site_name: 2022 February Common Fund Hackathon

theme:
  name: material
  palette:
    primary: white

docs_dir: ./docs

nav:
    - Home: index.md
    - Session Details: about.md
    - Schedule: schedule.md
    - Continued CFDE Engagement: engagement.md
    - Code of Conduct: CODEOFCONDUCT.md
    - Contributing: CONTRIBUTING.md
    - License: LICENSE.md
